trigger: none
  # branches:
  #   include:
  #     - main

variables:
  azureSubscription: 'Pay-as-you-go-sc'
  location: 'eastus'
  bicepFile: 'sqlserver.bicep'

stages:
  - stage: CreateAzureSQLServer
    displayName: 'CheckOut Code'
    jobs:
      - deployment: CreateSQLServer
        environment: 'dev'
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                
                - task: PublishBuildArtifacts@1
                  displayName: 'Publish Bicep Artifact'
                  inputs:
                    pathtoPublish: '$(System.DefaultWorkingDirectory)'
                    artifactName: 'bicep'
                    publishLocation: 'Container'

  - stage: ValidateSQLServerBicep
    dependsOn: CreateAzureSQLServer
    displayName: 'Validate Bicep Template'
    jobs:
        steps:
                - task: AzureResourceManagerTemplateDeployment@3
                  inputs:
                    deploymentScope: 'Resource Group'
                    azureResourceManagerConnection: '$(azureSubscription)'
                    subscriptionId: '6f0f938c-0599-4b69-9b56-09468ec24549'
                    location: '$(location)'
                    resourceGroupName: 'khrg'
                    templateLocation: 'Linked artifact'
                    csmFile: '$(bicepFile)'
                    csmParametersFile: 'sqlserver.parameters.json'
                    deploymentMode: 'Validation' 

  - stage: DeployAzureSQLServer
    displayName: 'Deploy Bicep Template'
    jobs:
        steps:
                - task: AzureResourceManagerTemplateDeployment@3
                  dependsOn: ValidateSQLServerBicep
                  displayName: 'Bicep to Deploy SQLvServer'
                  inputs:
                    deploymentScope: 'Resource Group'
                    azureResourceManagerConnection: '$(azureSubscription)'
                    subscriptionId: '6f0f938c-0599-4b69-9b56-09468ec24549'
                    action: 'Create Or Update Resource Group'
                    resourceGroupName: 'khrg'
                    location: '$(location)'
                    templateLocation: 'Linked artifact'
                    csmFile: '$(bicepFile)'
                    csmParametersFile: 'sqlserver.parameters.json'
                    deploymentMode: 'Incremental'